name: Quick Tests

on:
  pull_request:
    paths-ignore:
    - 'doc/**'
  push:

jobs:
  FreeBSD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Start FreeBSD VM
        uses: vmactions/freebsd-vm@v1
        with:
          prepare: pkg install -y bash cmake
          sync: 'rsync'
          copyback: false
      - name: super-test
        shell: freebsd {0}
        run: |
            cd ${{ github.workspace }}
            ./super-test.sh cmake
